# NUMPY

In [3]:
import numpy as np
print(np.__version__) #numpyversion

1.16.5


# ARRAYS

In [7]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr1)
print(arr2)
print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# ndim

In [5]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays

In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# INDEXING

In [9]:
arr = np.array([1, 2, 3, 4])                                         #1Darray
print(arr[0])

1


In [10]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])                          #2Darray
print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


In [11]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  #3Darray
print(arr[0, 1, 2])

6


In [12]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])                          #negativeindexing
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# ArraySlicing

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])                     #1Darray
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [20]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])    #2Darray
print(arr[1, 1:4])
print(arr[0:2, 1:4])

[7 8 9]
[[2 3 4]
 [7 8 9]]


# arraydatatype

In [6]:
ar1 = np.array([1, 2, 3, 4])
print(arr.dtype)
ar2 = np.array(['apple', 'banana', 'cherry'])
print(ar2.dtype)

int32
<U6


In [10]:
ar3 = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [11]:
ar4 = np.array([1.1, 2.1, 3.1])    #changingdatatype
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32


In [ ]:
#COPY vs VIEW

In [14]:
ar5 = np.array([1, 2, 3, 4, 5])
x = ar5.copy()
ar5[0] = 42
print(ar5)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [16]:
y = ar5.view()
ar5[0] = 42
print(ar5)
print(y)


[42  2  3  4  5]
[42  2  3  4  5]


In [17]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


# Shape and Reshape

In [18]:
ar6 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(ar6.shape)

(2, 4)


In [5]:
ar7 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(ar7.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


# Iterating

In [6]:
ar8 = np.array([1, 2, 3])
for x in ar8:
  print(x)

1
2
3


In [8]:
ar9 = np.array([[1, 2, 3], [4, 5, 6]])
for x in ar9:
  for y in x:
    print(y)

1
2
3
4
5
6


# NumPy Joining Array

In [11]:
ar10 = np.array([1, 2, 3])
ar11 = np.array([4, 5, 6])
arr = np.concatenate((ar10, ar11))
print(arr)

[1 2 3 4 5 6]


In [12]:
array = np.stack((ar10, ar11), axis=1)
print(array)

[[1 4]
 [2 5]
 [3 6]]


In [17]:
array1 = np.hstack((ar10, ar11))
print(array1)
array2 =  np.vstack((ar10, ar11))
print(array2)
array3 = np.dstack((ar10, ar11))
print(array3)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [3]:
import re

In [5]:
txt = "The rain in Spain"
x = re.search("^The.*Spain$", txt)

In [ ]:
#Camelcase

In [6]:
import camelcase
c = camelcase.CamelCase()
txt = "hello world"
print(c.hump(txt))

ModuleNotFoundError: No module named 'camelcase'

# string format()

In [9]:
price = 49
price1= 50
x = "The price is {} dollars"
print(x.format(price1))


The price is 50 dollars


In [11]:
open("my_txt.txt",'r').readline()

FileNotFoundError: [Errno 2] No such file or directory: 'my_txt.txt'